# Generated by Django 4.0.3 on 2022-04-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_news', '0002_alter_post_author_alter_post_categorytype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoryType',
            new_name='type',
        ),
    ]
